language: r
#r: bioc-release
#cache: packages
cache: false
latex: false
r:
  #- 3.1.3
  #- 3.2.5
  #- 3.3.3
  #- 3.4.4
  - 3.5.0
  #- devel
warnings_are_errors: true
sudo: required
apt_packages:
  - libfftw3-dev
bioc_packages:
  - EBImage
r_packages:
  - covr
  - cli
  - rlang
after_success:
  - Rscript -e 'covr::codecov()'
