language: r
cache: packages
latex: false
r:
  #- 3.1.3
  #- 3.2.5
  #- 3.3.3
  - 3.4.4
  - 3.5.0
  #- devel
warnings_as_errors: true
before_install:
  - sudo apt-get install libfftw3-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_r covr
  #- ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc_deps
sudo: required
r_packages:
  - covr
after_success:
  #- Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'
