language: r
cache: packages
latex: false
r:
  #- 3.1.3
  #- 3.2.5
  #- 3.3.3
  - 3.4.4
  - 3.5.0
  #- devel
warnings_are_errors: true
apt_packages:
  - libfftw3-dev
sudo: required
r_packages:
  - covr
bioc_pakages:
  - EBImage (>= 4.6.0)
after_success:
  #- Rscript -e 'covr::coveralls()'
  - Rscript -e 'covr::codecov()'
