language: r
cache: packages
r:
#  - 3.1.3
#  - 3.2.5
#  - 3.3.0
#  - 3.3.1
#  - 3.3.2
#  - 3.3.3
  - 3.4.0
  - devel
warnings_as_errors: true

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  #- ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc_deps

